---
# tasks file for ansible-role-docker-host

- name: "Include OS Specific Playbook"
  include: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"
